# Generated by Django 4.2.2 on 2023-07-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_useraccount_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='username',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
