# Generated by Django 4.2.2 on 2023-06-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_fileaccess_file_access_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileaccess',
            name='permission',
            field=models.CharField(choices=[('editor', 'EDIT'), ('viewer', 'VIEW'), ('commentor', 'COMMENT')], max_length=100),
        ),
    ]
