# Generated by Django 4.2.2 on 2023-06-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_alter_fileaccess_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileaccess',
            name='permission',
            field=models.CharField(choices=[('editor', 'EDIT'), ('viewer', 'VIEW'), ('commentor', 'COMMENT')], default='viewer', max_length=100),
        ),
    ]
