# Generated by Django 4.2.2 on 2023-06-30 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_alter_fileaccess_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('permissions', models.CharField(choices=[('editor', 'EDIT'), ('viewer', 'VIEW'), ('commentor', 'COMMENT')], default='viewer', max_length=100)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_access', to='storage.file')),
            ],
        ),
    ]
