# Generated by Django 4.2.2 on 2023-06-30 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_sendaccess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='access_permission',
        ),
        migrations.DeleteModel(
            name='FileAccess',
        ),
    ]
