# Generated by Django 4.2.2 on 2023-06-30 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_remove_file_access_permission_delete_fileaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendaccess',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='send_access', to='storage.file'),
        ),
    ]
