# Generated by Django 4.2.2 on 2023-07-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_alter_sendaccess_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_content',
        ),
        migrations.AddField(
            model_name='file',
            name='file_url',
            field=models.URLField(blank=True),
        ),
    ]
