# Generated by Django 4.2.2 on 2023-07-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0009_remove_file_file_content_file_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_url',
            field=models.FileField(upload_to=''),
        ),
    ]
